# Generated by Django 6.0.6 on 2026-07-22 08:35

import hosting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_event_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(upload_to=hosting.models.event_poster_upload_path),
        ),
    ]
