# Generated by Django 6.0.6 on 2026-07-21 10:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(upload_to=accounts.models.profile_image_upload_path),
        ),
    ]
